import type { Metadata } from "next";
import { PropsWithChildren } from "react";

import Layout from "@/components/custom/Layout";
import { baseUrl } from "@/lib/base-url";

import "./global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(baseUrl),
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
};

export default RootLayout;
